<template><div><!-- @format -->
<h2 id="列表和键" tabindex="-1"><a class="header-anchor" href="#列表和键"><span>列表和键</span></a></h2>
<p>在 React 中，经常需要根据数组中的数据项渲染列表。正确地处理列表和键（Keys）对于性能优化和组件的正确行为至关重要。</p>
<h3 id="_1-渲染列表" tabindex="-1"><a class="header-anchor" href="#_1-渲染列表"><span>1. 渲染列表</span></a></h3>
<p>使用 JavaScript 的<code v-pre>map</code>函数在 JSX 中渲染数组中的每一项。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token keyword">function</span> <span class="token function">ItemList</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> items <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>ul</span><span class="token punctuation">></span></span><span class="token plain-text">
      </span><span class="token punctuation">{</span>items<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">item</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span><span class="token punctuation">></span></span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>text<span class="token punctuation">}</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
      <span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token plain-text">
    </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>ul</span><span class="token punctuation">></span></span>
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-使用键-keys" tabindex="-1"><a class="header-anchor" href="#_2-使用键-keys"><span>2. 使用键（Keys）</span></a></h3>
<p>为列表中的每个元素分配一个唯一的键（key），以帮助 React 识别哪些元素改变了、添加了或者被移除了。</p>
<h3 id="_3-键的类型" tabindex="-1"><a class="header-anchor" href="#_3-键的类型"><span>3. 键的类型</span></a></h3>
<p>键可以是数字、字符串或是元素在数组中的位置，但最佳实践是使用稳定的身份标识符。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token punctuation">{</span>
  items<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">item</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span><span class="token punctuation">></span></span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>text<span class="token punctuation">}</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_4-避免使用数组索引作为键" tabindex="-1"><a class="header-anchor" href="#_4-避免使用数组索引作为键"><span>4. 避免使用数组索引作为键</span></a></h3>
<p>如果列表项可以重新排序，尽量避免使用数组索引作为键，因为这会导致性能问题和组件状态的错误。</p>
<h3 id="_5-键的稳定性" tabindex="-1"><a class="header-anchor" href="#_5-键的稳定性"><span>5. 键的稳定性</span></a></h3>
<p>键应该是稳定的、可预测的，且在组件的整个生命周期内不会变化。</p>
<h3 id="_6-键的作用" tabindex="-1"><a class="header-anchor" href="#_6-键的作用"><span>6. 键的作用</span></a></h3>
<p>键帮助 React 识别哪些元素是不同的，从而优化 DOM 操作和更新。</p>
<h3 id="_7-没有键的后果" tabindex="-1"><a class="header-anchor" href="#_7-没有键的后果"><span>7. 没有键的后果</span></a></h3>
<p>如果不提供键，React 会使用数组索引作为默认键，这可能会导致性能下降和组件状态不一致。</p>
<h3 id="_8-在复杂数据结构中使用键" tabindex="-1"><a class="header-anchor" href="#_8-在复杂数据结构中使用键"><span>8. 在复杂数据结构中使用键</span></a></h3>
<p>当渲染对象数组时，确保每个对象有一个唯一的键。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token punctuation">{</span>
  users<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">user</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token class-name">User</span></span>
      <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>user<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span>
      <span class="token spread"><span class="token punctuation">{</span><span class="token operator">...</span>user<span class="token punctuation">}</span></span>
    <span class="token punctuation">/></span></span>
  <span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_9-列表的动态变化" tabindex="-1"><a class="header-anchor" href="#_9-列表的动态变化"><span>9. 列表的动态变化</span></a></h3>
<p>当列表数据发生变化（添加、删除、排序）时，键能够帮助 React 正确地更新 DOM。</p>
<h3 id="_10-使用react-fragment优化列表" tabindex="-1"><a class="header-anchor" href="#_10-使用react-fragment优化列表"><span>10. 使用<code v-pre>React.Fragment</code>优化列表</span></a></h3>
<p>当渲染多个元素而不想添加额外的 DOM 元素时，可以使用<code v-pre>React.Fragment</code>。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token keyword">function</span> <span class="token function">ItemList</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> items <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token class-name">React.Fragment</span></span><span class="token punctuation">></span></span><span class="token plain-text">
      </span><span class="token punctuation">{</span>items<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">item</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span><span class="token punctuation">></span></span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>text<span class="token punctuation">}</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
      <span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token plain-text">
    </span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token class-name">React.Fragment</span></span><span class="token punctuation">></span></span>
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_11-使用key属性" tabindex="-1"><a class="header-anchor" href="#_11-使用key属性"><span>11. 使用<code v-pre>key</code>属性</span></a></h3>
<p>在渲染数组元素时，通过<code v-pre>key</code>属性传递键。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_12-避免在元素间共享键" tabindex="-1"><a class="header-anchor" href="#_12-避免在元素间共享键"><span>12. 避免在元素间共享键</span></a></h3>
<p>每个元素的键应该是唯一的，不要在整个应用程序中共享键。</p>
<h3 id="_13-键和性能" tabindex="-1"><a class="header-anchor" href="#_13-键和性能"><span>13. 键和性能</span></a></h3>
<p>正确使用键可以提高渲染性能，尤其是在大规模列表渲染时。</p>
<h3 id="_14-条件渲染列表" tabindex="-1"><a class="header-anchor" href="#_14-条件渲染列表"><span>14. 条件渲染列表</span></a></h3>
<p>可以在<code v-pre>map</code>回调函数中进行条件渲染。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token punctuation">{</span>
  items
    <span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">item</span><span class="token punctuation">)</span> <span class="token operator">=></span> item<span class="token punctuation">.</span>isVisible<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">item</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">key</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>id<span class="token punctuation">}</span></span><span class="token punctuation">></span></span><span class="token punctuation">{</span>item<span class="token punctuation">.</span>text<span class="token punctuation">}</span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_15-使用usememo优化列表" tabindex="-1"><a class="header-anchor" href="#_15-使用usememo优化列表"><span>15. 使用<code v-pre>useMemo</code>优化列表</span></a></h3>
<p>如果列表渲染涉及到高开销的操作，可以使用<code v-pre>useMemo</code>进行优化。</p>
<div class="language-jsx line-numbers-mode" data-ext="jsx" data-title="jsx"><pre v-pre class="language-jsx"><code><span class="token keyword">const</span> items <span class="token operator">=</span> <span class="token function">useMemo</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">computeExpensiveList</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">[</span>data<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


