<template><div><h2 id="ts-编译选项" tabindex="-1"><a class="header-anchor" href="#ts-编译选项"><span>ts 编译选项</span></a></h2>
<h3 id="include-指定需要编译的文件" tabindex="-1"><a class="header-anchor" href="#include-指定需要编译的文件"><span>include 指定需要编译的文件</span></a></h3>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><pre v-pre class="language-json"><code>include<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"./src/**/*"</span><span class="token punctuation">]</span> <span class="token comment">// (src: src 目录下 \*_: 任意目录 _: 任意文件)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="exclude-排除不需要编译的文件" tabindex="-1"><a class="header-anchor" href="#exclude-排除不需要编译的文件"><span>exclude 排除不需要编译的文件</span></a></h3>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><pre v-pre class="language-json"><code><span class="token comment">// (默认值: ["node_modules", "bower_components", "jspm_packages"])</span>
exclude<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"./src/assets.....自己写"</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="files-文件名" tabindex="-1"><a class="header-anchor" href="#files-文件名"><span>files: [ ... 文件名 ]</span></a></h3>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><pre v-pre class="language-json"><code><span class="token comment">//只有文件少的时候, 用一个数组来统计编译的文件就行了</span>
files<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"./src/index.ts"</span><span class="token punctuation">,</span> <span class="token string">"./src/other.ts"</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="compileroptions-配置选项" tabindex="-1"><a class="header-anchor" href="#compileroptions-配置选项"><span>compilerOptions 配置选项</span></a></h3>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><pre v-pre class="language-json"><code><span class="token property">"compilerOptions"</span><span class="token operator">:</span><span class="token punctuation">{</span>
  <span class="token property">"target"</span><span class="token operator">:</span> <span class="token string">"es5"</span><span class="token punctuation">,</span> <span class="token comment">// 指定编译后的版本</span>
  <span class="token property">"module"</span><span class="token operator">:</span> <span class="token string">"es6"</span><span class="token punctuation">,</span> <span class="token comment">// 指定要使用的模块化的规范 commonjs es6</span>
  <span class="token property">"lib"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"dom"</span><span class="token punctuation">,</span> <span class="token string">"dom.iterable"</span><span class="token punctuation">,</span> <span class="token string">"esnext"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token comment">// 指定项目中用到的库 es6 promise...</span>
  <span class="token property">"outDir"</span><span class="token operator">:</span> <span class="token string">"./dist"</span><span class="token punctuation">,</span> <span class="token comment">// 指定输出目录</span>
  <span class="token property">"outFile"</span><span class="token operator">:</span> <span class="token string">"./dist/app.js"</span><span class="token punctuation">,</span> <span class="token comment">// 将代码合并为一个文件</span>
  <span class="token property">"allowJs"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 是否对js文件进行编译, 默认为false</span>
  <span class="token property">"checkJs"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 是否检查js语法符合规范, 默认为false</span>
  <span class="token property">"removeComments"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">// 是否移除注释, 默认为false</span>
  <span class="token property">"noEmit"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 不生成编译后所产生的js文件, 默认为false</span>
  <span class="token property">"noEmitOnError"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 报错时不生成编译文件, 默认为false</span>
  <span class="token property">"awaysStrict"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 设置编译后的文件是否使用严格模式, 默认为false</span>
  <span class="token property">"noImplicitAny"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 不允许隐式的any类型设置, 默认为false</span>
  <span class="token property">"noImplicitThis"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 不允许不明确类型的this, 默认为false</span>
  <span class="token property">"strictNullChecks"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// 严格的检查空值, 默认为false</span>
  <span class="token property">"strict"</span><span class="token operator">:</span> <span class="token boolean">false</span> <span class="token comment">// 所有的检查的总开关, 如果设置为true, 所有的都打开了就不用写了</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


